name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn eslint . --ext .js

  api-call:
    # needs: lint
    # Esto lo podríamos tener si quisieramos que se ejecute después del lint y solo si se linteó bien 
    runs-on: ubuntu-latest
    steps:
    - name: Hacer POST
      run: |
          echo "SABEEEE"
          curl -X POST https://pokemon-api-vpmj.onrender.com/cards \
          -H "Content-Type: application/json" \
          -d '{"nombre": "Pokemon bakano",
                  "tipo": "Agua",
                  "faseEvolucion": "Fase 1",
                  "puntosSalud": 690,
                  "ataques": [
                  {
                    "nombre": "Lanzallamas",
                    "costoEnergia": ["Fuego", "Fuego", "Incolora"],
                    "danio": "100",
                    "descripcion": "Quema al Pokémon Defensor"
                  }
                  ]
              }' 
              echo "POST se ha hecho, esto aparece en el output de github?"
              echo "Código de respuesta recibido: $response_code"

  update-readme:
    # needs: api-call
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Actualizar versión en README
      run: |
        # Busca la línea de versión y extrae el número actual
        current_version=$(grep -oP 'Versión actual: v\d+\.\d+\.\d+' README.md | grep -oP '\d+\.\d+\.\d+')
        
        # Incrementa el número de patch (último dígito)
        new_version=$(echo $current_version | awk -F. '{$NF++; print}' OFS=.)
        
        # Reemplaza en el archivo
        sed -i "s/Versión actual: v$current_version/Versión actual: v$new_version/" README.md
        
        echo "Versión actualizada de v$current_version a v$new_version"
        
    - name: Commit y push de los cambios
      run: |
        git add README.md
        git commit -m "Auto-increment version to v$(grep -oP 'Versión actual: v\d+\.\d+\.\d+' README.md | grep -oP '\d+\.\d+\.\d+') [skip ci]"
        git push