name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn eslint . --ext .js

  api-call:
    # needs: lint
    # Esto lo podríamos tener si quisieramos que se ejecute después del lint y solo si se linteó bien 
    runs-on: ubuntu-latest
    steps:
    - name: Hacer POST
      run: |
          echo "SABEEEE"
          curl -X POST https://pokemon-api-vpmj.onrender.com/cards \
          -H "Content-Type: application/json" \
          -d '{"nombre": "Pokemon bakano",
                  "tipo": "Fuegooooooo",
                  "faseEvolucion": "Fase 24",
                  "puntosSalud": 690,
                  "ataques": [
                    {
                      "nombre": "Lanzallamas",
                      "costoEnergia": ["Fuego", "Fuego", "Incolora"],
                      "danio": "100",
                      "descripcion": "Quema al Pokémon Defensor"
                    }
                  ]
                }'
              echo "POST se ha hecho, esto aparece en el output de github?"
              echo "Código de respuesta recibido: $response_code"

  update-readme:
    needs: api-call
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # README update steps will go here