name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn eslint . --ext .js

  api-call:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # API call steps will go here

  update-readme:
    needs: api-call
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # README update steps will go here